services:
  anpr:
    image: czdanika/anpr-projekt:latest
    ports:
      - "${ANPR_PORT:-5555}:${ANPR_PORT:-5555}"
    volumes:
      - ./anpr-data/vehicles.db:/app/vehicles.db
      - ./anpr-data/received_images:/app/received_images
    restart: unless-stopped
    environment:
      - ANPR_PORT=${ANPR_PORT:-5555}
      - ANPR_ADMIN_PASSWORD=${ANPR_ADMIN_PASSWORD:-password123}
      - ANPR_USER_PASSWORD=${ANPR_USER_PASSWORD:-userpassword}
