version: "3.8"
services:
  anpr:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - ANPR_ADMIN_PASSWORD=password123
      - ANPR_USER_PASSWORD=userpassword
