version: "3.8"
services:
  anpr:
    build: .
    ports:
      - "${ANPR_PORT:-5555}:${ANPR_PORT:-5555}"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - ANPR_PORT=${ANPR_PORT:-5555}
      - ANPR_ADMIN_PASSWORD=${ANPR_ADMIN_PASSWORD:-password123}
      - ANPR_USER_PASSWORD=${ANPR_USER_PASSWORD:-userpassword}
      - TZ=Europe/Budapest
